/**
 * D&D 5e Nexus - Monster Bestiary Dataset (SRD)
 */
window.DnDNexus = window.DnDNexus || {};

window.DnDNexus.monstersList = [
  {
    id: 'm-goblin',
    name: 'Goblin',
    type: 'Küçük İnsansı (Goblinoid)',
    cr: '1/4',
    ac: 15,
    hp: 7,
    speed: '9m',
    str: 8, dex: 14, con: 10, int: 10, wis: 8, cha: 8,
    traits: 'Nimble Escape: Bonus aksiyon olarak Disengage veya Hide yapabilir.',
    actions: 'Scimitar: +4 vurur, 1d6+2 kesici. Shortbow: +4 vurur, 1d6+2 delici (80/320 ft).'
  },
  {
    id: 'm-kobold',
    name: 'Kobold',
    type: 'Küçük İnsansı (Draconic)',
    cr: '1/8',
    ac: 12,
    hp: 5,
    speed: '9m',
    str: 7, dex: 15, con: 9, int: 8, wis: 7, cha: 8,
    traits: 'Pack Tactics: Müttefiki hedefin 5 ft yakınındaysa avantajlı vurur. Sunlight Sensitivity: Gün ışığında dezavantajlıdır.',
    actions: 'Dagger: +4 vurur, 1d4+2 delici. Sling: +4 vurur, 1d4+2 delici.'
  },
  {
    id: 'm-skeleton',
    name: 'İskelet (Skeleton)',
    type: 'Orta Hortlak (Undead)',
    cr: '1/4',
    ac: 13,
    hp: 13,
    speed: '9m',
    str: 10, dex: 14, con: 15, int: 6, wis: 8, cha: 5,
    traits: 'Vulnerabilities: Ezici (Bludgeoning) hasara karşı hassastır.',
    actions: 'Shortsword: +4 vurur, 1d6+2 delici. Shortbow: +4 vurur, 1d6+2 delici.'
  },
  {
    id: 'm-zombie',
    name: 'Zombi (Zombie)',
    type: 'Orta Hortlak (Undead)',
    cr: '1/4',
    ac: 8,
    hp: 22,
    speed: '6m',
    str: 13, dex: 6, con: 16, int: 3, wis: 6, cha: 5,
    traits: 'Undead Fortitude: Canı 0\'a düştüğünde CON zarı atarak (DC 5 + hasar) 1 HP ile hayatta kalabilir.',
    actions: 'Slam: +3 vurur, 1d6+1 ezici hasar.'
  },
  {
    id: 'm-orc',
    name: 'Ork (Orc)',
    type: 'Orta İnsansı (Orc)',
    cr: '1/2',
    ac: 13,
    hp: 15,
    speed: '9m',
    str: 16, dex: 12, con: 16, int: 7, wis: 11, cha: 10,
    traits: 'Aggressive: Bonus aksiyon olarak düşmana doğru tam hız koşabilir.',
    actions: 'Greataxe: +5 vurur, 1d12+3 kesici hasar. Javelin: +5 vurur, 1d6+3 delici.'
  },
  {
    id: 'm-bandit',
    name: 'Haydut (Bandit)',
    type: 'Orta İnsansı (Humanoid)',
    cr: '1/8',
    ac: 12,
    hp: 11,
    speed: '9m',
    str: 11, dex: 12, con: 12, int: 10, wis: 10, cha: 10,
    traits: 'Parry: Reaksiyon olarak AC\'sini +2 arttırır.',
    actions: 'Scimitar: +3 vurur, 1d6+1 kesici. Light Crossbow: +3 vurur, 1d8+1 delici.'
  },
  {
    id: 'm-bugbear',
    name: 'Bugbear',
    type: 'Orta İnsansı (Goblinoid)',
    cr: '1',
    ac: 16,
    hp: 27,
    speed: '9m',
    str: 15, dex: 14, con: 13, int: 8, wis: 11, cha: 9,
    traits: 'Brute: Melee silahı fazladan 1 zar atar. Surprise Attack: Sürpriz elde ederse +2d6 fazladan hasar verir.',
    actions: 'Morningstar: +4 vurur, 2d8+2 ezici/delici. Javelin: +4 vurur, 1d6+2 delici.'
  },
  {
    id: 'm-ogre',
    name: 'Ogre',
    type: 'Büyük Dev (Giant)',
    cr: '2',
    ac: 11,
    hp: 59,
    speed: '12m',
    str: 19, dex: 8, con: 16, int: 5, wis: 7, cha: 7,
    traits: 'Girişken Dev: Yüksek can ve vurucu güce sahip ağır yakın dövüşçü.',
    actions: 'Greatclub: +6 vurur, 2d8+4 ezici. Javelin: +6 vurur, 2d6+4 delici.'
  },
  {
    id: 'm-mimic',
    name: 'Mimik (Mimic)',
    type: 'Orta Yaratık (Monstrosity)',
    cr: '2',
    ac: 12,
    hp: 58,
    speed: '4.5m',
    str: 17, dex: 12, con: 15, int: 5, wis: 13, cha: 8,
    traits: 'Shapechanger: Sandık veya mobilya kılığına girer. Adhesive: Temas eden yaratık yapışır (Grappled DC 13).',
    actions: 'Pseudopod: +5 vurur, 1d8+3 ezici. Bite: +5 vurur, 1d8+3 ezici + 1d8 asit.'
  },
  {
    id: 'm-young-red-dragon',
    name: 'Genç Kırmızı Ejderha (Young Red Dragon)',
    type: 'Büyük Ejderha (Dragon)',
    cr: '10',
    ac: 18,
    hp: 178,
    speed: '12m, Uçuş: 24m',
    str: 23, dex: 10, con: 21, int: 14, wis: 11, cha: 19,
    traits: 'Multiattack: 1 Isırık ve 2 Pençe saldırısı yapar.',
    actions: 'Bite: +10 vurur, 2d10+6 delme + 2d6 ateş. Fire Breath (Recharge 5-6): 30ft koni, 16d6 ateş hasarı (DEX Save 17).'
  },
  {
    id: 'm-beholder',
    name: 'Beholder (Gözlücü)',
    type: 'Büyük Aberasyon (Aberration)',
    cr: '13',
    ac: 18,
    hp: 180,
    speed: 'Uçuş: 6m (Hover)',
    str: 10, dex: 14, con: 18, int: 17, wis: 15, cha: 17,
    traits: 'Antimagic Cone: Ana gözü 150ft alanda tüm büyüleri büyüsüzleştirir.',
    actions: 'Eye Rays: Her tur rastgele 3 göz ışını atar (Charm, Paralyzing, Fear, Slowing, Death Ray, Disintegration Ray).'
  },
  {
    id: 'm-lich',
    name: 'Lich',
    type: 'Orta Hortlak (Undead Spellcaster)',
    cr: '21',
    ac: 17,
    hp: 135,
    speed: '9m',
    str: 11, dex: 16, con: 16, int: 20, wis: 14, cha: 16,
    traits: 'Legendary Resistance (3/Day), Rejuvenation (Phylactery), 9. Seviye Büyücü (Power Word Kill, Time Stop).',
    actions: 'Paralyzing Touch: +12 vurur, 3d6 soğuk + Felç (CON Save 18). Efsanevi Aksiyonlar (Ray of Frost, Disrupt Life).'
  },
  {
    id: 'm-giant-rat',
    name: 'Dev Fare (Giant Rat)',
    type: 'Küçük Yaratık (Beast)',
    cr: '1/8',
    ac: 12,
    hp: 7,
    speed: '6m',
    str: 7, dex: 15, con: 11, int: 2, wis: 10, cha: 4,
    traits: 'Pack Tactics: Müttefiki hedefin 5 ft yakınındaysa avantajlı vurur.',
    actions: 'Bite: +4 vurur, 1d4+2 delici.'
  },
  {
    id: 'm-wolf',
    name: 'Kurt (Wolf)',
    type: 'Orta Yaratık (Beast)',
    cr: '1/4',
    ac: 13,
    hp: 11,
    speed: '12m',
    str: 12, dex: 15, con: 12, int: 3, wis: 12, cha: 6,
    traits: 'Pack Tactics, Keen Hearing and Smell.',
    actions: 'Bite: +4 vurur, 2d4+2 delici; hedef DC 11 STR kurtarma atışını kaçırırsa yere düşer (Prone).'
  },
  {
    id: 'm-hobgoblin',
    name: 'Hobgoblin',
    type: 'Orta İnsansı (Goblinoid)',
    cr: '1/2',
    ac: 18,
    hp: 11,
    speed: '9m',
    str: 13, dex: 12, con: 12, int: 10, wis: 10, cha: 9,
    traits: 'Martial Advantage: Bir müttefiki hedefin 5 ft yakınındaysa turda bir kez +2d6 fazladan hasar verir.',
    actions: 'Longsword: +3 vurur, 1d8+1 kesici. Longbow: +3 vurur, 1d8+1 delici.'
  },
  {
    id: 'm-ghoul',
    name: 'Gul (Ghoul)',
    type: 'Orta Hortlak (Undead)',
    cr: '1',
    ac: 12,
    hp: 22,
    speed: '9m',
    str: 13, dex: 15, con: 10, int: 7, wis: 10, cha: 6,
    traits: 'Undead, Zehire Bağışıklık.',
    actions: 'Bite: +2 vurur, 2d6+2 delici. Claws: +4 vurur, 2d4+2 kesici + Felç (CON Save 10, Elfler etkilenmez).'
  },
  {
    id: 'm-giant-spider',
    name: 'Dev Örümcek (Giant Spider)',
    type: 'Büyük Yaratık (Beast)',
    cr: '1',
    ac: 14,
    hp: 26,
    speed: '9m, Tırmanma: 9m',
    str: 14, dex: 16, con: 12, int: 2, wis: 11, cha: 4,
    traits: 'Spider Climb, Web Sense, Web Walker.',
    actions: 'Bite: +5 vurur, 1d8+3 delici + 2d8 zehir (DC 11 CON, başarılıysa yarı hasar). Web (Recharge 5-6): 5/60ft menzil, DC 12 STR yoksa hedef ağa yapışır.'
  },
  {
    id: 'm-owlbear',
    name: 'Baykuşayı (Owlbear)',
    type: 'Büyük Yaratık (Monstrosity)',
    cr: '3',
    ac: 13,
    hp: 59,
    speed: '12m',
    str: 20, dex: 12, con: 17, int: 3, wis: 12, cha: 7,
    traits: 'Keen Sight and Smell.',
    actions: 'Multiattack: Gaga ve Pençe saldırısı yapar. Beak: +7 vurur, 1d10+5 delici. Claws: +7 vurur, 2d8+5 kesici.'
  },
  {
    id: 'm-gelatinous-cube',
    name: 'Jelatinimsi Küp (Gelatinous Cube)',
    type: 'Büyük Yaratık (Ooze)',
    cr: '2',
    ac: 6,
    hp: 84,
    speed: '4.5m',
    str: 14, dex: 3, con: 20, int: 1, wis: 6, cha: 1,
    traits: 'Transparent (görünmesi zor), Engulf: hareket ederken üstünden geçtiği hedefi yutabilir.',
    actions: 'Pseudopod: +5 vurur, 3d6+2 asit. Engulf: DC 12 DEX yoksa hedef yutulur ve 3d6 asit hasarı alır.'
  },
  {
    id: 'm-wight',
    name: 'Wight',
    type: 'Orta Hortlak (Undead)',
    cr: '3',
    ac: 14,
    hp: 45,
    speed: '9m',
    str: 15, dex: 14, con: 16, int: 10, wis: 13, cha: 15,
    traits: 'Undead, Sunlight Sensitivity: gün ışığında dezavantajlıdır.',
    actions: 'Multiattack: 2 Life Drain veya kılıç saldırısı. Life Drain: +4 vurur, 1d6+2 nekrotik + hedefin can maksimumu düşer. Longsword: +4 vurur, 1d8+2 kesici.'
  },
  {
    id: 'm-ettin',
    name: 'Ettin',
    type: 'Dev İki Başlı (Giant)',
    cr: '4',
    ac: 12,
    hp: 85,
    speed: '9m',
    str: 21, dex: 8, con: 17, int: 6, wis: 10, cha: 8,
    traits: 'İki Kafa: Algı kontrollerinde avantajlı, biri uyanıkken sürpriz atağa uğramaz.',
    actions: 'Multiattack: Balta ve Topuz saldırısı. Battleaxe: +9 vurur, 2d8+5 kesici. Morningstar: +9 vurur, 2d8+5 delici.'
  },
  {
    id: 'm-troll',
    name: 'Trol (Troll)',
    type: 'Büyük Dev (Giant)',
    cr: '5',
    ac: 15,
    hp: 84,
    speed: '9m',
    str: 18, dex: 13, con: 20, int: 7, wis: 9, cha: 7,
    traits: 'Regeneration: Ateş/asit hasarı almadığı sürece her tur başı 10 HP yeniler. Keen Smell.',
    actions: 'Multiattack: Isırık ve 2 Pençe. Bite: +9 vurur, 1d6+4 delici. Claw: +9 vurur, 2d6+4 kesici.'
  },
  {
    id: 'm-hill-giant',
    name: 'Tepe Devi (Hill Giant)',
    type: 'Dev (Giant)',
    cr: '5',
    ac: 13,
    hp: 105,
    speed: '12m',
    str: 21, dex: 8, con: 19, int: 5, wis: 9, cha: 6,
    traits: 'Kaba kuvvet ve büyük can havuzuyla ön saf tehdidi.',
    actions: 'Multiattack: 2 Topuz saldırısı. Greatclub: +9 vurur, 3d8+6 ezici. Rock: +9 vurur, 3d10+6 ezici (60/240ft).'
  },
  {
    id: 'm-frost-giant',
    name: 'Buz Devi (Frost Giant)',
    type: 'Dev (Giant)',
    cr: '8',
    ac: 15,
    hp: 149,
    speed: '12m',
    str: 23, dex: 9, con: 21, int: 9, wis: 10, cha: 12,
    traits: 'Soğuğa Bağışıklık.',
    actions: 'Multiattack: 2 Balta saldırısı. Greataxe: +12 vurur, 3d12+7 kesici. Rock: +12 vurur, 3d10+7 ezici.'
  },
  {
    id: 'm-fire-giant',
    name: 'Ateş Devi (Fire Giant)',
    type: 'Dev (Giant)',
    cr: '9',
    ac: 18,
    hp: 162,
    speed: '9m',
    str: 25, dex: 9, con: 23, int: 10, wis: 14, cha: 13,
    traits: 'Ateşe Bağışıklık.',
    actions: 'Multiattack: 2 Kılıç saldırısı. Greatsword: +11 vurur, 6d6+7 kesici. Rock: +11 vurur, 4d10+7 ezici.'
  },
  {
    id: 'm-vampire',
    name: 'Vampir (Vampire)',
    type: 'Orta Hortlak (Undead)',
    cr: '13',
    ac: 16,
    hp: 144,
    speed: '9m, Tırmanma: 9m',
    str: 18, dex: 18, con: 18, int: 17, wis: 15, cha: 18,
    traits: 'Shapechanger (Yarasa/Sis formu), Regeneration, Spider Climb, Legendary Resistance (3/gün).',
    actions: 'Multiattack: 2 Pençe veya Charm+Isırık. Claw: +9 vurur, 2d6+4 kesici. Bite: +9 vurur, 1d6 delici + 3d6 nekrotik + can emer.'
  },
  {
    id: 'm-death-knight',
    name: 'Ölüm Şövalyesi (Death Knight)',
    type: 'Orta Hortlak (Undead Spellcaster)',
    cr: '17',
    ac: 20,
    hp: 180,
    speed: '9m',
    str: 20, dex: 11, con: 18, int: 12, wis: 16, cha: 18,
    traits: 'Aura of Despair (korkutur), Legendary Resistance (3/gün), 9. Seviye Büyücü.',
    actions: 'Multiattack: 2 Kılıç saldırısı. Greatsword: +10 vurur, 2d6+5 kesici + 1d8 nekrotik. Hellfire Orb (Recharge 5-6): DC 18 DEX, 10d6 ateş + 10d6 nekrotik.'
  },
  {
    id: 'm-balor',
    name: 'Balor',
    type: 'Büyük İblis (Fiend, Demon)',
    cr: '19',
    ac: 19,
    hp: 262,
    speed: '12m, Uçuş: 18m',
    str: 26, dex: 15, con: 22, int: 20, wis: 16, cha: 22,
    traits: 'Death Throes (öldüğünde 20ft alanda 70 ateş hasarı patlar), Fire Aura, Magic Resistance, Ateşe Bağışıklık.',
    actions: 'Multiattack: Kılıç ve Kırbaç. Longsword: +14 vurur, 3d10+8 kesici + 3d8 ateş. Whip: +14 vurur, 2d6+8 ateş + hedefi 25ft çeker.'
  },
  {
    id: 'm-pit-fiend',
    name: 'Çukur İblisi (Pit Fiend)',
    type: 'Büyük İblis (Fiend, Devil)',
    cr: '20',
    ac: 19,
    hp: 336,
    speed: '9m, Uçuş: 18m',
    str: 26, dex: 14, con: 24, int: 22, wis: 18, cha: 24,
    traits: 'Fear Aura, Magic Resistance, Ateş & Zehire Bağışıklık.',
    actions: 'Multiattack: Isırık + 2 Pençe + Topuz. Bite: +14 vurur, 4d6+8 delici + 6d6 zehir. Mace: +14 vurur, 2d6+8 ezici + 6d10 ateş.'
  }
];
